package com.aritu.java.eu.text;

import java.text.DateFormatSymbols;

import com.aritu.java.eu.constants.Locales;

public final class BasqueDateFormatSymbols extends DateFormatSymbols {

    private static final long serialVersionUID = 1L;

    private static final String[] BASQUE_MONTHS = { "urtarrila", "otsaila",
            "martxoa", "apirila", "maiatza", "ekaina", "uztaila", "abuztua",
            "iraila", "urria", "azaroa", "abendua", "" };

    private static final String[] BASQUE_SHORT_MONTHS = { "urt", "ots", "mar",
            "api", "mai", "eka", "uzt", "abu", "ira", "urr", "aza", "abe", "" };

    private static final String[] BASQUE_SHORT_WEEKDAYS = { "", "ig.", "al.",
            "ar.", "az.", "og.", "ol.", "lr." };

    private static final String[] BASQUE_WEEKDAYS = { "", "igandea",
            "astelehena", "asteartea", "asteazkena", "osteguna", "ostirala",
            "larunbata" };

    private static final String[][] BASQUE_ZONE_STRINGS = {
            { "America/Los_Angeles", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "PST", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "America/Denver", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "MST", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Phoenix", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "PNT", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Chicago", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "CST", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/New_York", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "EST", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Indianapolis", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "IET", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "Pacific/Honolulu", "Hawaiiko ordu estandarra", "HST",
                    "Hawaiiko udako ordua", "HDT" },
            { "HST", "Hawaiiko ordu estandarra", "HST", "Hawaiiko udako ordua",
                    "HDT" },
            { "America/Anchorage", "Alaskako ordu estandarra", "AKST",
                    "Alaskako udako ordua", "AKDT" },
            { "AST", "Alaskako ordu estandarra", "AKST", "Alaskako udako ordua",
                    "AKDT" },
            { "America/Halifax", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/St_Johns", "Ternuako ordu estandarra", "NST",
                    "Ternuako udako ordua", "NDT" },
            { "CNT", "Ternuako ordu estandarra", "NST", "Ternuako udako ordua",
                    "NDT" },
            { "Europe/Paris", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "ECT", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "GMT", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Casablanca", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "Asia/Jerusalem", "Israelgo ordu estandarra", "IST",
                    "Israelgo udako ordua", "IDT" },
            { "Asia/Tokyo", "Japoniako ordu estandarra", "JST",
                    "Japoniako udako ordua", "JDT" },
            { "JST", "Japoniako ordu estandarra", "JST",
                    "Japoniako udako ordua", "JDT" },
            { "Europe/Bucharest", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Asia/Shanghai", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "CTT", "Txinako ordu estandarra", "CST", "Txinako udako ordua",
                    "CDT" },
            { "ACT", "Erdialdeko ordu estandarra (iparraldeko eremua)", "CST",
                    "Erdialdeko udako ordua (iparraldeko eremua)", "CST" },
            { "AET", "Ekialdeko ordu estandarra (Hegoaldeko Gales Berria)",
                    "EST", "Ekialdeko udako ordua (Hegoaldeko Gales Berria)",
                    "EST" },
            { "AGT", "Argentinako ordua", "ART", "Argentinako udako ordua",
                    "ARST" },
            { "ART", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Africa/Abidjan", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Accra", "Ghana erdialdeko ordua", "GMT",
                    "Ghanako udako ordua", "GHST" },
            { "Africa/Addis_Ababa", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Algiers", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Africa/Asmara", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Asmera", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Bamako", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Bangui", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Banjul", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Bissau", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Blantyre", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Brazzaville", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Bujumbura", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Cairo", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Africa/Ceuta", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Africa/Conakry", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Dakar", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Dar_es_Salaam", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Djibouti", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Douala", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/El_Aaiun", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "Africa/Freetown", "Greenwich meridianoko ordua", "GMT",
                    "Sierra Leonako udako ordua", "SLST" },
            { "Africa/Gaborone", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Harare", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Johannesburg", "Hegoafrikako ordu estandarra", "SAST",
                    "Hegoafrikako udako ordua", "SAST" },
            { "Africa/Kampala", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Khartoum", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Kigali", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Kinshasa", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Lagos", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Libreville", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Lome", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Luanda", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Lubumbashi", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Lusaka", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Malabo", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Maputo", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "Africa/Maseru", "Hegoafrikako ordu estandarra", "SAST",
                    "Hegoafrikako udako ordua", "SAST" },
            { "Africa/Mbabane", "Hegoafrikako ordu estandarra", "SAST",
                    "Hegoafrikako udako ordua", "SAST" },
            { "Africa/Mogadishu", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Monrovia", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Nairobi", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Africa/Ndjamena", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Niamey", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Nouakchott", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Ouagadougou", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Porto-Novo", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "Africa/Sao_Tome", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Timbuktu", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Africa/Tripoli", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Africa/Tunis", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Africa/Windhoek", "Afrika mendebaldeko ordua", "WAT",
                    "Afrika mendebaldeko udako ordua", "WAST" },
            { "America/Adak", "Hawaii-Aleutiarretako ordu estandarra", "HAST",
                    "Hawaii-Aleutiarretako udako ordua", "HADT" },
            { "America/Anguilla", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Antigua", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Araguaina", "Brasilgo ordua", "BRT",
                    "Brasilgo udako ordua", "BRST" },
            { "America/Argentina/Buenos_Aires", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Catamarca", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/ComodRivadavia", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Cordoba", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Jujuy", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/La_Rioja", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Mendoza", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Rio_Gallegos", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Salta", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/San_Juan", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/San_Luis", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Tucuman", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Argentina/Ushuaia", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Aruba", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Asuncion", "Paraguaiko ordua", "PYT",
                    "Paraguaiko udako ordua", "PYST" },
            { "America/Atikokan", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Atka", "Hawaii-Aleutiarretako ordu estandarra", "HAST",
                    "Hawaii-Aleutiarretako udako ordua", "HADT" },
            { "America/Bahia", "Brasilgo ordua", "BRT", "Brasilgo udako ordua",
                    "BRST" },
            { "America/Barbados", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Belem", "Brasilgo ordua", "BRT", "Brasilgo udako ordua",
                    "BRST" },
            { "America/Belize", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Blanc-Sablon", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Boa_Vista", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/Bogota", "Kolonbiako ordua", "COT",
                    "Kolonbiako udako ordua", "COST" },
            { "America/Boise", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Buenos_Aires", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Cambridge_Bay", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Campo_Grande", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/Cancun", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Caracas", "Venezuelako ordua", "VET",
                    "Venezuelako udako ordua", "VEST" },
            { "America/Catamarca", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Cayenne", "Guyana Frantseseko ordua", "GFT",
                    "Guyana Frantseseko udako ordua", "GFST" },
            { "America/Cayman", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Chihuahua", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Coral_Harbour", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Cordoba", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Costa_Rica", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Cuiaba", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/Curacao", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Danmarkshavn", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "America/Dawson", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "America/Dawson_Creek", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Detroit", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Dominica", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Edmonton", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Eirunepe", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/El_Salvador", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Ensenada", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "America/Fort_Wayne", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Fortaleza", "Brasilgo ordua", "BRT",
                    "Brasilgo udako ordua", "BRST" },
            { "America/Glace_Bay", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Godthab", "Groenlandia mendebaldeko ordua", "WGT",
                    "Groenlandia mendebaldeko udako ordua", "WGST" },
            { "America/Goose_Bay", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Grand_Turk", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Grenada", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Guadeloupe", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Guatemala", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Guayaquil", "Ekuadorgo ordua", "ECT",
                    "Ekuadorgo udako ordua", "ECST" },
            { "America/Guyana", "Guyanako ordua", "GYT", "Guyanako udako ordua",
                    "GYST" },
            { "America/Havana", "Kubako ordua", "CST", "Kubako udako ordua",
                    "CDT" },
            { "America/Hermosillo", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Indiana/Indianapolis", "Ekialdeko ordu estandarra",
                    "EST", "Ekialdeko udako ordua", "EDT" },
            { "America/Indiana/Knox", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Indiana/Marengo", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Indiana/Petersburg", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Indiana/Tell_City", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Indiana/Vevay", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Indiana/Vincennes", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Indiana/Winamac", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Inuvik", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Iqaluit", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Jamaica", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Jujuy", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Juneau", "Alaskako ordu estandarra", "AKST",
                    "Alaskako udako ordua", "AKDT" },
            { "America/Kentucky/Louisville", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Kentucky/Monticello", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Knox_IN", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/La_Paz", "Boliviako ordua", "BOT",
                    "Boliviako udako ordua", "BOST" },
            { "America/Lima", "Peruko ordua", "PET", "Peruko udako ordua",
                    "PEST" },
            { "America/Louisville", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Maceio", "Brasilgo ordua", "BRT", "Brasilgo udako ordua",
                    "BRST" },
            { "America/Managua", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Manaus", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/Marigot", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Martinique", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Mazatlan", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/Mendoza", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Menominee", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Merida", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Mexico_City", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Miquelon", "Saint-Pierre eta Mikeluneko ordu estandarra",
                    "PMST", "Saint-Pierre eta Mikeluneko udako ordua", "PMDT" },
            { "America/Moncton", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Montevideo", "Uruguaiko ordua", "UYT",
                    "Uruguaiko udako ordua", "UYST" },
            { "America/Monterrey", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Montreal", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Montserrat", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Nassau", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Nipigon", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Nome", "Alaskako ordu estandarra", "AKST",
                    "Alaskako udako ordua", "AKDT" },
            { "America/Noronha", "Fernando de Noronhako ordua", "FNT",
                    "Fernando de Noronhako udako ordua", "FNST" },
            { "America/North_Dakota/Center", "Erdialdeko ordu estandarra",
                    "CST", "Erdialdeko udako ordua", "CDT" },
            { "America/North_Dakota/New_Salem", "Erdialdeko ordu estandarra",
                    "CST", "Erdialdeko udako ordua", "CDT" },
            { "America/Panama", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Pangnirtung", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Paramaribo", "Surinamgo ordua", "SRT",
                    "Surinamgo udako ordua", "SRST" },
            { "America/Port-au-Prince", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Port_of_Spain", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Porto_Acre", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/Porto_Velho", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/Puerto_Rico", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Rainy_River", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Rankin_Inlet", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Recife", "Brasilgo ordua", "BRT", "Brasilgo udako ordua",
                    "BRST" },
            { "America/Regina", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Resolute", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Rio_Branco", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "America/Rosario", "Argentinako ordua", "ART",
                    "Argentinako udako ordua", "ARST" },
            { "America/Santarem", "Brasilgo ordua", "BRT",
                    "Brasilgo udako ordua", "BRST" },
            { "America/Santiago", "Txileko ordua", "CLT", "Txileko udako ordua",
                    "CLST" },
            { "America/Santo_Domingo", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Sao_Paulo", "Brasilgo ordua", "BRT",
                    "Brasilgo udako ordua", "BRST" },
            { "America/Scoresbysund", "Groenlandia ekialdeko ordua", "EGT",
                    "Groenlandia ekialdeko udako ordua", "EGST" },
            { "America/Shiprock", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "America/St_Barthelemy", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/St_Kitts", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/St_Lucia", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/St_Thomas", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/St_Vincent", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Swift_Current", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Tegucigalpa", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Thule", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Thunder_Bay", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Tijuana", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "America/Toronto", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "America/Tortola", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Vancouver", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "America/Virgin", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "America/Whitehorse", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "America/Winnipeg", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "America/Yakutat", "Alaskako ordu estandarra", "AKST",
                    "Alaskako udako ordua", "AKDT" },
            { "America/Yellowknife", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "Antarctica/Casey", "Mendebaldeko ordu estandarra (Australia)",
                    "WST", "Mendebaldeko udako ordua (Australia)", "WST" },
            { "Antarctica/Davis", "Daviseko ordua", "DAVT",
                    "Daviseko udako ordua", "DAVST" },
            { "Antarctica/DumontDUrville", "Dumont-d'Urvilleko ordua", "DDUT",
                    "Dumont-d'Urvilleko udako ordua", "DDUST" },
            { "Antarctica/Mawson", "Mawsongo ordua", "MAWT",
                    "Mawsongo udako ordua", "MAWST" },
            { "Antarctica/McMurdo", "Zeelanda Berriko ordu estandarra", "NZST",
                    "Zeelanda Berriko udako ordua", "NZDT" },
            { "Antarctica/Palmer", "Txileko ordua", "CLT",
                    "Txileko udako ordua", "CLST" },
            { "Antarctica/Rothera", "Rotherako ordua", "ROTT",
                    "Rotherako udako ordua", "ROTST" },
            { "Antarctica/South_Pole", "Zeelanda Berriko ordu estandarra",
                    "NZST", "Zeelanda Berriko udako ordua", "NZDT" },
            { "Antarctica/Syowa", "Syowako ordua", "SYOT",
                    "Syowako udako ordua", "SYOST" },
            { "Antarctica/Vostok", "Vostokeko ordua", "VOST",
                    "Vostokeko udako ordua", "VOSST" },
            { "Arctic/Longyearbyen", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Asia/Aden", "Arabiako ordu estandarra", "AST",
                    "Arabiako udako ordua", "ADT" },
            { "Asia/Almaty", "Almatyko ordua", "ALMT", "Almatyko udako ordua",
                    "ALMST" },
            { "Asia/Amman", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Asia/Anadyr", "Anadyrgo ordua", "ANAT", "Anadyrgo udako ordua",
                    "ANAST" },
            { "Asia/Aqtau", "Aktauko ordua", "AQTT", "Aktauko udako ordua",
                    "AQTST" },
            { "Asia/Aqtobe", "Aktobeko ordua", "AQTT", "Aktobeko udako ordua",
                    "AQTST" },
            { "Asia/Ashgabat", "Turkmenistango ordua", "TMT",
                    "Turkmenistango udako ordua", "TMST" },
            { "Asia/Ashkhabad", "Turkmenistango ordua", "TMT",
                    "Turkmenistango udako ordua", "TMST" },
            { "Asia/Baghdad", "Arabiako ordu estandarra", "AST",
                    "Arabiako udako ordua", "ADT" },
            { "Asia/Bahrain", "Arabiako ordu estandarra", "AST",
                    "Arabiako udako ordua", "ADT" },
            { "Asia/Baku", "Azerbaijango ordua", "AZT",
                    "Azerbaijango udako ordua", "AZST" },
            { "Asia/Bangkok", "Indotxinako ordua", "ICT",
                    "Indotxinako udako ordua", "ICST" },
            { "Asia/Beirut", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Asia/Bishkek", "Kirgizistango ordua", "KGT",
                    "Kirgizistango udako ordua", "KGST" },
            { "Asia/Brunei", "Bruneiko ordua", "BNT", "Bruneiko udako ordua",
                    "BNST" },
            { "Asia/Calcutta", "Indiako ordu estandarra", "IST",
                    "Indiako udako ordua", "IDT" },
            { "Asia/Choibalsan", "Txoibalsango ordua", "CHOT",
                    "Txoibalsango udako ordua", "CHOST" },
            { "Asia/Chongqing", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Chungking", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Colombo", "Indiako ordu estandarra", "IST",
                    "Indiako udako ordua", "IDT" },
            { "Asia/Dacca", "Bangladeshko ordua", "BDT",
                    "Bangladeshko udako ordua", "BDST" },
            { "Asia/Dhaka", "Bangladeshko ordua", "BDT",
                    "Bangladeshko udako ordua", "BDST" },
            { "Asia/Dili", "Ekialdeko Timorgo ordua", "TLT",
                    "Ekialdeko Timorgo udako ordua", "TLST" },
            { "Asia/Damascus", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Asia/Dubai", "Golkoko ordu estandarra", "GST",
                    "Golkoko udako ordua", "GDT" },
            { "Asia/Dushanbe", "Taijikistango ordua", "TJT",
                    "Taijikistango udako ordua", "TJST" },
            { "Asia/Gaza", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Asia/Harbin", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Ho_Chi_Minh", "Indotxinako ordua", "ICT",
                    "Indotxinako udako ordua", "ICST" },
            { "Asia/Hong_Kong", "Hong Kongeko ordua", "HKT",
                    "Hong Kongeko udako ordua", "HKST" },
            { "Asia/Hovd", "Hovdeko ordua", "HOVT", "Hovdeko udako ordua",
                    "HOVST" },
            { "Asia/Irkutsk", "Irkutskeko ordua", "IRKT",
                    "Irkutskeko udako ordua", "IRKST" },
            { "Asia/Istanbul", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Asia/Jakarta", "Indonesia mendebaldeko ordua", "WIT",
                    "Indonesia mendebaldeko udako ordua", "WIST" },
            { "Asia/Jayapura", "Indonesia ekialdeko ordua", "EIT",
                    "Indonesia ekialdeko udako ordua", "EIST" },
            { "Asia/Kabul", "Afganistango ordua", "AFT",
                    "Afganistango udako ordua", "AFST" },
            { "Asia/Kamchatka", "Petropavlovsk-Kamtxatskiko ordua", "PETT",
                    "Petropavlovsk-Kamtxatskiko udako ordua", "PETST" },
            { "Asia/Karachi", "Pakistango ordua", "PKT",
                    "Pakistango udako ordua", "PKST" },
            { "Asia/Kashgar", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Katmandu", "Nepalgo ordua", "NPT", "Nepaldo udako ordua",
                    "NPST" },
            { "Asia/Kolkata", "Indiako ordu estandarra", "IST",
                    "Indiako udako ordua", "IDT" },
            { "Asia/Krasnoyarsk", "Krasnoiarskeko ordua", "KRAT",
                    "Krasnoiarskeko udako ordua", "KRAST" },
            { "Asia/Kuala_Lumpur", "Malaysiako ordua", "MYT",
                    "Malaysiako udako ordua", "MYST" },
            { "Asia/Kuching", "Malaysiako ordua", "MYT",
                    "Malaysiako udako ordua", "MYST" },
            { "Asia/Kuwait", "Arabiako ordu estandarra", "AST",
                    "Arabiako udako ordua", "ADT" },
            { "Asia/Macao", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Macau", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Magadan", "Magadango ordua", "MAGT",
                    "Magadango udako ordua", "MAGST" },
            { "Asia/Makassar", "Indonesia erdialdeko ordua", "CIT",
                    "Indonesia erdialdeko udako ordua", "CIST" },
            { "Asia/Manila", "Filipinetako ordua", "PHT",
                    "Filipinetako udako ordua", "PHST" },
            { "Asia/Muscat", "Golkoko ordu estandarra", "GST",
                    "Golkoko udako ordua", "GDT" },
            { "Asia/Nicosia", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Asia/Novosibirsk", "Novosibirskeko ordua", "NOVT",
                    "Novosibirskeko udako ordua", "NOVST" },
            { "Asia/Oral", "Oralgo ordua", "ORAT", "Oralgo udako ordua",
                    "ORAST" },
            { "Asia/Omsk", "Omskeko ordua", "OMST", "Omskeko udako ordua",
                    "OMSST" },
            { "Asia/Phnom_Penh", "Indotxinako ordua", "ICT",
                    "Indotxinako udako ordua", "ICST" },
            { "Asia/Pontianak", "Indonesia mendebaldeko ordua", "WIT",
                    "Indonesia mendebaldeko udako ordua", "WIST" },
            { "Asia/Pyongyang", "Koreako ordu estandarra", "KST",
                    "Koreako udako ordua", "KDT" },
            { "Asia/Qatar", "Arabiako ordu estandarra", "AST",
                    "Arabiako udako ordua", "ADT" },
            { "Asia/Qyzylorda", "Kyzylordako ordua", "QYZT",
                    "Kyzylordako udako ordua", "QYZST" },
            { "Asia/Rangoon", "Myanmargo ordua", "MMT", "Myanmargo udako ordua",
                    "MMST" },
            { "Asia/Riyadh", "Arabiako ordu estandarra", "AST",
                    "Arabiako udako ordua", "ADT" },
            { "Asia/Saigon", "Indotxinako ordua", "ICT",
                    "Indotxinako udako ordua", "ICST" },
            { "Asia/Sakhalin", "Sakhalingo ordua", "SAKT",
                    "Sakhalingo udako ordua", "SAKST" },
            { "Asia/Samarkand", "Uzbekistango ordua", "UZT",
                    "Uzbekistango udako ordua", "UZST" },
            { "Asia/Seoul", "Koreako ordu estandarra", "KST",
                    "Koreako udako ordua", "KDT" },
            { "Asia/Singapore", "Singapurgo ordua", "SGT",
                    "Singapurgo udako ordua", "SGST" },
            { "Asia/Taipei", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Tel_Aviv", "Israelgo ordu estandarra", "IST",
                    "Israelgo udako ordua", "IDT" },
            { "Asia/Tashkent", "Uzbekistango ordua", "UZT",
                    "Uzbekistango udako ordua", "UZST" },
            { "Asia/Tbilisi", "Georgiako ordua", "GET", "Georgiako udako ordua",
                    "GEST" },
            { "Asia/Tehran", "Irango ordu estandarra", "IRST",
                    "Irango udako ordua", "IRDT" },
            { "Asia/Thimbu", "Bhutango ordua", "BTT", "Bhutango udako ordua",
                    "BTST" },
            { "Asia/Thimphu", "Bhutango ordua", "BTT", "Bhutango udako ordua",
                    "BTST" },
            { "Asia/Ujung_Pandang", "Indonesia erdialdeko ordua", "CIT",
                    "Indonesia erdialdeko udako ordua", "CIST" },
            { "Asia/Ulaanbaatar", "Ulan Batorreko ordua", "ULAT",
                    "Ulan Batorreko udako ordua", "ULAST" },
            { "Asia/Ulan_Bator", "Ulan Batorreko ordua", "ULAT",
                    "Ulan Batorreko udako ordua", "ULAST" },
            { "Asia/Urumqi", "Txinako ordu estandarra", "CST",
                    "Txinako udako ordua", "CDT" },
            { "Asia/Vientiane", "Indotxinako ordua", "ICT",
                    "Indotxinako udako ordua", "ICST" },
            { "Asia/Vladivostok", "Vladivostokeko ordua", "VLAT",
                    "Vladivostokeko udako ordua", "VLAST" },
            { "Asia/Yakutsk", "Jakutskeko ordua", "YAKT",
                    "Jakutskeko udako ordua", "YAKST" },
            { "Asia/Yekaterinburg", "Ekaterinburgeko ordua", "YEKT",
                    "Ekaterinburgeko udako ordua", "YEKST" },
            { "Asia/Yerevan", "Armeniako ordua", "AMT", "Armeniako udako ordua",
                    "AMST" },
            { "Atlantic/Azores", "Azoreetako ordua", "AZOT",
                    "Azoreetako udako ordua", "AZOST" },
            { "Atlantic/Bermuda", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "Atlantic/Canary", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "Atlantic/Cape_Verde", "Cabo Verdeko udako ordua", "CVT",
                    "Cabo Verdeko udako ordua", "CVST" },
            { "Atlantic/Faeroe", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "Atlantic/Faroe", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "Atlantic/Jan_Mayen", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Atlantic/Madeira", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "Atlantic/Reykjavik", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Atlantic/South_Georgia", "Hego Georgiako ordu estandarra", "GST",
                    "Hego Georgiako udako ordua", "GDT" },
            { "Atlantic/St_Helena", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Atlantic/Stanley", "Malvina uharteetako ordua", "FKT",
                    "Malvina uharteetako udako ordua", "FKST" },
            { "Australia/ACT",
                    "Ekialdeko ordu estandarra (Hegoaldeko Gales Berria)",
                    "EST", "Ekialdeko udako ordua (Hegoaldeko Gales Berria)",
                    "EST" },
            { "Australia/Adelaide",
                    "Erdialdeko ordu estandarra (Australia Hegoaldea)", "CST",
                    "Erdialdeko udako ordua (Australia Hegoaldea)", "CST" },
            { "Australia/Brisbane", "Ekialdeko ordu estandarra (Queensland)",
                    "EST", "Ekialdeko udako ordua (Queensland)", "EST" },
            { "Australia/Broken_Hill",
                    "Erdialdeko ordu estandarra (Australia Hegoaldea/Hegoaldeko Gales Berria)",
                    "CST",
                    "Erdialdeko udako ordua (Australia Hegoaldea/Hegoaldeko Gales Berria)",
                    "CST" },
            { "Australia/Canberra",
                    "Ekialdeko ordu estandarra (Hegoaldeko Gales Berria)",
                    "EST", "Ekialdeko udako ordua (Hegoaldeko Gales Berria)",
                    "EST" },
            { "Australia/Currie",
                    "Ekialdeko ordu estandarra (Hegoaldeko Gales Berria)",
                    "EST", "Ekialdeko udako ordua (Hegoaldeko Gales Berria)",
                    "EST" },
            { "Australia/Darwin",
                    "Erdialdeko ordu estandarra (iparraldeko eremua)", "CST",
                    "Erdialdeko udako ordua (iparraldeko eremua)", "CST" },
            { "Australia/Eucla",
                    "Erdialdeko ordu estandarra-Occidental (Australia)", "CWST",
                    "Erdialdeko udako ordua-Occidental (Australia)", "CWST" },
            { "Australia/Hobart", "Ekialdeko ordu estandarra (Tasmania)", "EST",
                    "Ekialdeko udako ordua (Tasmania)", "EST" },
            { "Australia/LHI", "Lord Howeko ordu estandarra", "LHST",
                    "Lord Howeko ordu estandarra", "LHST" },
            { "Australia/Lindeman", "Ekialdeko ordu estandarra (Queensland)",
                    "EST", "Ekialdeko udako ordua (Queensland)", "EST" },
            { "Australia/Lord_Howe", "Lord Howeko ordu estandarra", "LHST",
                    "Lord Howeko ordu estandarra", "LHST" },
            { "Australia/Melbourne", "Ekialdeko ordu estandarra (Victoria)",
                    "EST", "Ekialdeko udako ordua (Victoria)", "EST" },
            { "Australia/North",
                    "Erdialdeko ordu estandarra (iparraldeko eremua)", "CST",
                    "Erdialdeko udako ordua (iparraldeko eremua)", "CST" },
            { "Australia/NSW",
                    "Ekialdeko ordu estandarra (Hegoaldeko Gales Berria)",
                    "EST", "Ekialdeko udako ordua (Hegoaldeko Gales Berria)",
                    "EST" },
            { "Australia/Perth", "Mendebaldeko ordu estandarra (Australia)",
                    "WST", "Mendebaldeko udako ordua (Australia)", "WST" },
            { "Australia/Queensland", "Ekialdeko ordu estandarra (Queensland)",
                    "EST", "Ekialdeko udako ordua (Queensland)", "EST" },
            { "Australia/South",
                    "Erdialdeko ordu estandarra (Australia Hegoaldea)", "CST",
                    "Erdialdeko udako ordua (Australia Hegoaldea)", "CST" },
            { "Australia/Sydney",
                    "Ekialdeko ordu estandarra (Hegoaldeko Gales Berria)",
                    "EST", "Ekialdeko udako ordua (Hegoaldeko Gales Berria)",
                    "EST" },
            { "Australia/Tasmania", "Ekialdeko ordu estandarra (Tasmania)",
                    "EST", "Ekialdeko udako ordua (Tasmania)", "EST" },
            { "Australia/Victoria", "Ekialdeko ordu estandarra (Victoria)",
                    "EST", "Ekialdeko udako ordua (Victoria)", "EST" },
            { "Australia/West", "Mendebaldeko ordu estandarra (Australia)",
                    "WST", "Mendebaldeko udako ordua (Australia)", "WST" },
            { "Australia/Yancowinna",
                    "Erdialdeko ordu estandarra (Australia Hegoaldea/Hegoaldeko Gales Berria)",
                    "CST",
                    "Erdialdeko udako ordua (Australia Hegoaldea/Hegoaldeko Gales Berria)",
                    "CST" },
            { "BET", "Brasilgo ordua", "BRT", "Brasilgo udako ordua", "BRST" },
            { "BST", "Bangladeshko ordua", "BDT", "Bangladeshko udako ordua",
                    "BDST" },
            { "Brazil/Acre", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "Brazil/DeNoronha", "Fernando de Noronhako ordua", "FNT",
                    "Fernando de Noronhako udako ordua", "FNST" },
            { "Brazil/East", "Brasilgo ordua", "BRT", "Brasilgo udako ordua",
                    "BRST" },
            { "Brazil/West", "Amazoniako ordu estandarra", "AMT",
                    "Amazoniako udako ordua", "AMST" },
            { "Canada/Atlantic", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "Canada/Central", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "Canada/East-Saskatchewan", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "Canada/Eastern", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "Canada/Mountain", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "Canada/Newfoundland", "Ternuako ordu estandarra", "NST",
                    "Ternuako udako ordua", "NDT" },
            { "Canada/Pacific", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "Canada/Yukon", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "Canada/Saskatchewan", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "CAT", "Afrika erdialdeko ordua", "CAT",
                    "Afrika erdialdeko udako ordua", "CAST" },
            { "CET", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Chile/Continental", "Txileko ordua", "CLT",
                    "Txileko udako ordua", "CLST" },
            { "Chile/EasterIsland", "Pazko uharteko ordua", "EAST",
                    "Pazko uharteko udako ordua", "EASST" },
            { "CST6CDT", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "Cuba", "Kubako ordu estandarra", "CST", "Kubako udako ordua",
                    "CDT" },
            { "EAT", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "EET", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Egypt", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Eire", "Greenwich meridianoko ordua", "GMT",
                    "Irlandako udako ordua", "IST" },
            { "EST5EDT", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "Etc/Greenwich", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Etc/UCT", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" },
            { "Etc/Universal", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" },
            { "Etc/UTC", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" },
            { "Etc/Zulu", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" },
            { "Europe/Amsterdam", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Andorra", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Athens", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Belfast", "Greenwich meridianoko ordua", "GMT",
                    "Britainia Handiko udako ordua", "BST" },
            { "Europe/Belgrade", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Berlin", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Bratislava", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Brussels", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Budapest", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Chisinau", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Copenhagen", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Dublin", "Greenwich meridianoko ordua", "GMT",
                    "Irlandako udako ordua", "IST" },
            { "Europe/Gibraltar", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Guernsey", "Greenwich meridianoko ordua", "GMT",
                    "Britainia Handiko udako ordua", "BST" },
            { "Europe/Helsinki", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Isle_of_Man", "Greenwich meridianoko ordua", "GMT",
                    "Britainia Handiko udako ordua", "BST" },
            { "Europe/Istanbul", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Jersey", "Greenwich meridianoko ordua", "GMT",
                    "Britainia Handiko udako ordua", "BST" },
            { "Europe/Kaliningrad", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Kiev", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Lisbon", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "Europe/Ljubljana", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/London", "Greenwich meridianoko ordua", "GMT",
                    "Britainia Handiko udako ordua", "BST" },
            { "Europe/Luxembourg", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Madrid", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Malta", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Mariehamn", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Minsk", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Monaco", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Moscow", "Moskuko ordu estandarra", "MSK",
                    "Moskuko udako ordua", "MSD" },
            { "Europe/Nicosia", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Oslo", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Podgorica", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Prague", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Riga", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Rome", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Samara", "Samarako ordua", "SAMT", "Samarako udako ordua",
                    "SAMST" },
            { "Europe/San_Marino", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Sarajevo", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Simferopol", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Skopje", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Sofia", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Stockholm", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Tallinn", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Tirane", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Tiraspol", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Uzhgorod", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Vaduz", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Vatican", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Vienna", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Vilnius", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Volgograd", "Volgogradoko ordua", "VOLT",
                    "Volgogradoko udako ordua", "VOLST" },
            { "Europe/Warsaw", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Zagreb", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "Europe/Zaporozhye", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "Europe/Zurich", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "GB", "Greenwich meridianoko ordua", "GMT",
                    "Britainia Handiko udako ordua", "BST" },
            { "GB-Eire", "Greenwich meridianoko ordua", "GMT",
                    "Britainia Handiko udako ordua", "BST" },
            { "Greenwich", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Hongkong", "Hong Kongeko ordua", "HKT",
                    "Hong Kongeko udako ordua", "HKST" },
            { "Iceland", "Greenwich meridianoko ordua", "GMT",
                    "Greenwich meridianoko ordua", "GMT" },
            { "Iran", "Irango ordu estandarra", "IRST", "Irango udako ordua",
                    "IRDT" },
            { "IST", "Indiako ordu estandarra", "IST", "Indiako udako ordua",
                    "IDT" },
            { "Indian/Antananarivo", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Indian/Chagos", "Indiar Ozeanoko lurraldeko ordua", "IOT",
                    "Indiar Ozeanoko lurraldeko udako ordua", "IOST" },
            { "Indian/Christmas", "Christmas uharteko ordua", "CXT",
                    "Christmas uharteko udako ordua", "CXST" },
            { "Indian/Cocos", "Cocos uharteetako ordua", "CCT",
                    "Cocos uharteetako udako ordua", "CCST" },
            { "Indian/Comoro", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Indian/Kerguelen",
                    "Frantziaren Lurralde Austral eta Antartikoetako ordua",
                    "TFT",
                    "Frantziaren Lurralde Austral eta Antartikoetako udako ordua",
                    "TFST" },
            { "Indian/Mahe", "Seychelleseko ordua", "SCT",
                    "Seychelleseko udako ordua", "SCST" },
            { "Indian/Maldives", "Maldivetako ordua", "MVT",
                    "Maldivetako udako ordua", "MVST" },
            { "Indian/Mauritius", "Maurizioko ordua", "MUT",
                    "Maurizioko udako ordua", "MUST" },
            { "Indian/Mayotte", "Afrika ekialdeko ordua", "EAT",
                    "Afrika ekialdeko udako ordua", "EAST" },
            { "Indian/Reunion", "Reuniongo ordua", "RET",
                    "Reuniongo udako ordua", "REST" },
            { "Israel", "Israelgo ordu estandarra", "IST",
                    "Israelgo udako ordua", "IDT" },
            { "Jamaica", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "Japan", "Japoniako ordu estandarra", "JST",
                    "Japoniako udako ordua", "JDT" },
            { "Kwajalein", "Marshall uharteeetako ordua", "MHT",
                    "Marshall uharteeetako udako ordua", "MHST" },
            { "Libya", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "MET", "Europa erdialdeko ordua", "MET",
                    "Europa erdialdeko udako ordua", "MEST" },
            { "Mexico/BajaNorte", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "Mexico/BajaSur", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "Mexico/General", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "MIT", "Mendebaldeko Samoako ordua", "WST",
                    "Mendebaldeko Samoako udako ordua", "WSST" },
            { "MST7MDT", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "Navajo", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "NET", "Armeniako ordua", "AMT", "Armeniako udako ordua",
                    "AMST" },
            { "NST", "Zeelanda Berriko ordu estandarra", "NZST",
                    "Zeelanda Berriko udako ordua", "NZDT" },
            { "NZ", "Zeelanda Berriko ordu estandarra", "NZST",
                    "Zeelanda Berriko udako ordua", "NZDT" },
            { "NZ-CHAT", "Chathametako ordu estandarra", "CHAST",
                    "Chathametako udako ordua", "CHADT" },
            { "PLT", "Pakistango ordua", "PKT", "Pakistango udako ordua",
                    "PKST" },
            { "Portugal", "Europa mendebaldeko ordua", "WET",
                    "Europa mendebaldeko udako ordua", "WEST" },
            { "PRT", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "Pacific/Apia", "Mendebaldeko Samoako ordua", "WST",
                    "Mendebaldeko Samoako udako ordua", "WSST" },
            { "Pacific/Auckland", "Zeelanda Berriko ordu estandarra", "NZST",
                    "Zeelanda Berriko udako ordua", "NZDT" },
            { "Pacific/Chatham", "Chathametako ordu estandarra", "CHAST",
                    "Chathametako udako ordua", "CHADT" },
            { "Pacific/Easter", "Pazko uharteko ordua", "EAST",
                    "Pazko uharteko udako ordua", "EASST" },
            { "Pacific/Efate", "Vanuatuko ordua", "VUT",
                    "Vanuatuko udako ordua", "VUST" },
            { "Pacific/Enderbury", "Phoenix uharteetako ordua", "PHOT",
                    "Phoenix uharteetako udako ordua", "PHOST" },
            { "Pacific/Fakaofo", "Tokelauko ordua", "TKT",
                    "Tokelauko udako ordua", "TKST" },
            { "Pacific/Fiji", "Fijiko ordua", "FJT", "Fijiko udako ordua",
                    "FJST" },
            { "Pacific/Funafuti", "Tuvaluko ordua", "TVT",
                    "Tuvaluko udako ordua", "TVST" },
            { "Pacific/Galapagos", "Galapagoetako ordua", "GALT",
                    "Galapagoetako udako ordua", "GALST" },
            { "Pacific/Gambier", "Gambier uharteetako ordua", "GAMT",
                    "Gambier uharteetako udako ordua", "GAMST" },
            { "Pacific/Guadalcanal", "Salomon uharteetako ordua", "SBT",
                    "Salomon uharteetako udako ordua", "SBST" },
            { "Pacific/Guam", "Txamorroko ordu estandarra", "ChST",
                    "Txamorroko udako ordua", "ChDT" },
            { "Pacific/Johnston", "Hawaiiko ordu estandarra", "HST",
                    "Hawaiiko udako ordua", "HDT" },
            { "Pacific/Kiritimati", "Lerroko uharteetako ordua", "LINT",
                    "Lerroko uharteetako udako ordua", "LINST" },
            { "Pacific/Kosrae", "Kosraeko ordua", "KOST",
                    "Kosraeko udako ordua", "KOSST" },
            { "Pacific/Kwajalein", "Marshall uharteeetako ordua", "MHT",
                    "Marshall uharteeetako udako ordua", "MHST" },
            { "Pacific/Majuro", "Marshall uharteeetako ordua", "MHT",
                    "Marshall uharteeetako udako ordua", "MHST" },
            { "Pacific/Marquesas", "Markesetako ordua", "MART",
                    "Markesetako udako ordua", "MARST" },
            { "Pacific/Midway", "Samoako ordu estandarra", "SST",
                    "Samoako udako ordua", "SDT" },
            { "Pacific/Nauru", "Nauruko ordua", "NRT", "Nauruko udako ordua",
                    "NRST" },
            { "Pacific/Niue", "Niueko ordua", "NUT", "Niueko udako ordua",
                    "NUST" },
            { "Pacific/Norfolk", "Norfolkeko ordua", "NFT",
                    "Norfolkeko udako ordua", "NFST" },
            { "Pacific/Noumea", "Kaledonia Berriko ordua", "NCT",
                    "Kaledonia Berriko udako ordua", "NCST" },
            { "Pacific/Pago_Pago", "Samoako ordu estandarra", "SST",
                    "Samoako udako ordua", "SDT" },
            { "Pacific/Palau", "Palauko ordua", "PWT", "Palauko udako ordua",
                    "PWST" },
            { "Pacific/Pitcairn", "Pitcairngo ordu estandarra", "PST",
                    "Pitcairngo udako ordua", "PDT" },
            { "Pacific/Ponape", "Pohnpeiko ordua", "PONT",
                    "Pohnpeiko udako ordua", "PONST" },
            { "Pacific/Port_Moresby", "Papua Ginea Berriko ordua", "PGT",
                    "Papua Ginea Berriko udako ordua", "PGST" },
            { "Pacific/Rarotonga", "Cook uharteetako ordua", "CKT",
                    "Cook uharteetako udako ordua", "CKHST" },
            { "Pacific/Saipan", "Txamorroko ordu estandarra", "ChST",
                    "Txamorroko udako ordua", "ChDT" },
            { "Pacific/Samoa", "Samoako ordu estandarra", "SST",
                    "Samoako udako ordua", "SDT" },
            { "Pacific/Tahiti", "Tahitiko ordua", "TAHT",
                    "Tahitiko udako ordua", "TAHST" },
            { "Pacific/Tarawa", "Gilbert uharteetako ordua", "GILT",
                    "Gilbert uharteetako udako ordua", "GILST" },
            { "Pacific/Tongatapu", "Tongako ordua", "TOT",
                    "Tongako udako ordua", "TOST" },
            { "Pacific/Truk", "Trukeko ordua", "TRUT", "Trukeko udako ordua",
                    "TRUST" },
            { "Pacific/Wake", "Wakeko ordua", "WAKT", "Wakeko udako ordua",
                    "WAKST" },
            { "Pacific/Wallis", "Wallis eta Futunako ordua", "WFT",
                    "Wallis eta Futunako ordu estandarra", "WFST" },
            { "Pacific/Yap", "Trukeko ordua", "TRUT", "Trukeko udako ordua",
                    "TRUST" },
            { "Poland", "Europa erdialdeko ordua", "CET",
                    "Europa erdialdeko udako ordua", "CEST" },
            { "PRC", "Txinako ordu estandarra", "CST", "Txinako udako ordua",
                    "CDT" },
            { "PST8PDT", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "ROK", "Koreako ordu estandarra", "KST", "Koreako udako ordua",
                    "KDT" },
            { "Singapore", "Singapurgo ordua", "SGT", "Singapurgo udako ordua",
                    "SGST" },
            { "SST", "Salomon uharteetako ordua", "SBT",
                    "Salomon uharteetako udako ordua", "SBST" },
            { "SystemV/AST4", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "SystemV/AST4ADT", "Atlantikoko ordu estandarra", "AST",
                    "Atlantikoko udako ordua", "ADT" },
            { "SystemV/CST6", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "SystemV/CST6CDT", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "SystemV/EST5", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "SystemV/EST5EDT", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "SystemV/HST10", "Hawaiiko ordu estandarra", "HST",
                    "Hawaiiko udako ordua", "HDT" },
            { "SystemV/MST7", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "SystemV/MST7MDT", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "SystemV/PST8", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "SystemV/PST8PDT", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "SystemV/YST9", "Alaskako ordu estandarra", "AKST",
                    "Alaskako udako ordua", "AKDT" },
            { "SystemV/YST9YDT", "Alaskako ordu estandarra", "AKST",
                    "Alaskako udako ordua", "AKDT" },
            { "Turkey", "Europa ekialdeko ordua", "EET",
                    "Europa ekialdeko udako ordua", "EEST" },
            { "UCT", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" },
            { "Universal", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" },
            { "US/Alaska", "Alaskako ordu estandarra", "AKST",
                    "Alaskako udako ordua", "AKDT" },
            { "US/Aleutian", "Hawaii-Aleutiarretako ordu estandarra", "HAST",
                    "Hawaii-Aleutiarretako udako ordua", "HADT" },
            { "US/Arizona", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "US/Central", "Ekialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "US/Eastern", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "US/Hawaii", "Hawaiiko ordu estandarra", "HST",
                    "Hawaiiko udako ordua", "HDT" },
            { "US/Indiana-Starke", "Erdialdeko ordu estandarra", "CST",
                    "Erdialdeko udako ordua", "CDT" },
            { "US/East-Indiana", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "US/Michigan", "Ekialdeko ordu estandarra", "EST",
                    "Ekialdeko udako ordua", "EDT" },
            { "US/Mountain", "Mendialdeko ordu estandarra", "MST",
                    "Mendialdeko udako ordua", "MDT" },
            { "US/Pacific", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "US/Pacific-New", "Pazifikoko ordu estandarra", "PST",
                    "Pazifikoko udako ordua", "PDT" },
            { "US/Samoa", "Samoako ordu estandarra", "SST",
                    "Samoako udako ordua", "SDT" },
            { "UTC", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" },
            { "VST", "Indotxinako ordua", "ICT", "Indotxinako udako ordua",
                    "ICST" },
            { "W-SU", "Moskuko ordu estandarra", "MSK", "Moskuko udako ordua",
                    "MSD" },
            { "WET", "Mendebaldeko Europako ordua", "WET",
                    "Mendebaldeko Europako udako ordua", "WEST" },
            { "Zulu", "Ordu unibertsal koordinatua", "UTC",
                    "Ordu unibertsal koordinatua", "UTC" } };

    public BasqueDateFormatSymbols() {
        super(Locales.CASTILIAN);
        setMonths(BASQUE_MONTHS);
        setShortMonths(BASQUE_SHORT_MONTHS);
        setShortWeekdays(BASQUE_SHORT_WEEKDAYS);
        setWeekdays(BASQUE_WEEKDAYS);
        setZoneStrings(BASQUE_ZONE_STRINGS);
    }

}
